### ISSUE TITLE
YOUR_CLIENT_SECRETを平文でgit管理してしまう問題について

### ISSUE THREAD

**Issue by JunichiIto** [perfect-ruby-on-rails/awesome_events#45]
下記のコードでは`YOUR_CLIENT_SECRET`を平文でgit管理する前提のように見えます。

https://github.com/perfect-ruby-on-rails/awesome_events/blob/master/config/initializers/omniauth.rb#L3

パーフェクトRuby on Railsの説明を読んでも、本番環境はcredentialsを使うように書かれていますが、development/testに関しては特に注意喚起はありませんでした。

実際、本書で作るようなサンプルアプリケーションであれば実害はないのかもしれません。
とはいえ、本書の読者（おそらくRailsやwebアプリ開発初心者）が、「development/testなら平文でいいのか」と理解してしまうのはちょっと怖いです。
実際、フィヨルドブートキャンプ生がこのリポジトリをフォークして`YOUR_CLIENT_SECRET`を平文で書いたPRを作っている（＝publicなGitHubリポジトリにpushしている）のを見たとき、一瞬ぞっとしました。

実害のあるなしにかかわらず、「習慣として`YOUR_CLIENT_SECRET`に該当するような値はgit管理すべきでない」「開発環境であってもcredentialsや環境変数を使うべき」とした方が将来の大事故を防げると思うのですが、いかがでしょうか？

**Comment by willnet** [comment]
課題提起ありがとうございます！

開発やテスト用途でも秘密の文字列系は慎重に扱う必要がある、というのは書いておいたほうが良かったですね。

ちなみに @JunichiIto  さんはどうやってこのあたり管理していますか？大体dotenvを利用するか、credentialsをdevelopment環境やtest環境でも適用する、が多そうだな〜と思いつつも、デファクトと言えるものががない認識なのでいいやり方があったら知りたいです。

個人的には [palkan/anyway_config: Configuration library for Ruby gems and applications](https://github.com/palkan/anyway_config) 推しなのですが、パRailsで取り上げるには力が必要(多機能で説明が大変なので採用しづらい)なgemなので悩ましいな〜となっています

**Comment by JunichiIto** [comment]
> 開発やテスト用途でも秘密の文字列系は慎重に扱う必要がある、というのは書いておいたほうが良かったですね。

ですよね。その共通認識が確認できたのであればとりあえずOKです。
（本の記述はもう変えられませんし・・・）
というわけでこちらはcloseしておきますね。

> どうやってこのあたり管理していますか？
> デファクトと言えるものががない認識なのでいいやり方があったら知りたいです

めちゃ悩ましいやつですねw 僕もいいやり方を知りたいです。
僕はなんだかんだでdotenvを使うことが多いですかね〜。
anyway_config は初めて知りました。
